#!/bin/bash
echo "Enter File Name"
read file
if [ -f $file ]
then
        echo "File Found with a Name $file\n"
        count=0
        val=0

        while read line
                do
                val=$("$line" | wc -c)
                count=$((count+1))
                done < $file
        echo "Total Line in File : $count"
else
        echo "File Not Found check other file using running script"
fi
